### ISSUE TITLE
LittleFS Stream collides with Portenta Camera Stream

### ISSUE THREAD

**Issue by hpssjellis** [khoih-prog/LittleFS_Portenta_H7#1]
HI @khoih-prog, it has been a while.

I can provide more information but is it possible that the littleFS file stream collides with the Portenta camera data Stream?

I am trying to get Portenta or NiclaVision images onto the web using the Portenta webserver, but as soon as I load the camera it complains about not knowing which Stream to use.

**Comment by khoih-prog** [comment]
HI @hpssjellis 

Long time as well.

I'm afraid I can't help anything here as I don't have that kind of `Portenta Camera` hardware and haven't worked with Portenta for a while.

The best place to ask is Arduino `mbed_portenta` core with many good experts with the possession of all **hidden** info there.

Good Luck,

**Comment by hpssjellis** [comment]
Good idea @khoih-prog 

I will close this.
